#!/usr/bin/env bash

echo "php-cs-fixer pre commit hook start"

PHP_CS_FIXER="tools/php-cs-fixer/vendor/bin/php-cs-fixer"

if [ -x $PHP_CS_FIXER ]; then
      git status --porcelain | grep -E '^[^.D]+.php$' | cut -c 3- | while read -r line; do
          eval "$PHP_CS_FIXER fix --verbose $line";
          git add "$line";
      done
else
    echo "Please run \"cd tools/php-cs-fixer && composer install\""
fi

echo "php-cs-fixer pre commit hook finish"
